language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
notifications:
  email:
    on_success: never
env:
  global:
    - secure: ZwOoo8tMXIszfsrh2EkDKI60sxbcA+/Jjrz5Q7bwVhRS5Nmo2etkAfjnU/verqjvpG+EaS6ey44I10DJjKq7JpuZaIMZYOBB3oz+y4FUC8xhQ+Zw4jO1Yj/KvUCAxKZ0Qg6ySysyjPKXOrT9ExmVOevYfQYdj2GGsq79398JM7k=
    - secure: A970dUGDJ+oEfcCLdUmmPzceFJbDj+pBXi8tmExj1t4IIuRLngmRf1ZJklH3ok3ZceK8YssayClGy4yryW6/XWK1mwA18HB80iIxhNe3A7sxU88qaY/Fqvi9saJjHv/BKTPFA8b2BXsMNgK1306EgSdTbVDaNsoMIQk+7Rde2yg=
sudo: false
cache:
    directories:
        - node_modules
        - src/agrc
        - src/bootstrap
        - src/dijit
        - src/dojo
        - src/dojox
        - src/ijit
        - src/jasmine-favicon-reporter
        - src/stubmodule
        - src/util
        - src/jasmine-jsreporter
        - src/xstyle
